name::"Rafka Hendryan" 
title:"Mahasiswa | Web Enthusiast"
bio:"Halo Saya suka belajar coding dan membuat website."
avatar:""
social:
     github:"rafkahendryan-create"
     tiktok:@rafkamode.sigmasy
projects:
   -name:"Portofolio ini"
   description:"Website portofolio saya"
   url:"httpss://github.com/rafkahendryan-create/portofolioiku"
   name:"Proyek Sekolah"
   description:"Website gabut buat Portofolio"
   url:"https://link-proyek-saya.com"
